//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \GenerateUnits.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/anjdreas/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\UnitClasses\MyUnit.extra.cs files to add code to generated unit classes.
//     Add Extensions\MyUnitExtensions.cs to decorate unit classes with new behavior.
//     Add Scripts\UnitDefinitions\MyUnit.json and run GeneratUnits.bat to generate new units or unit classes.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2007 Andreas Gullberg Larsen (anjdreas@gmail.com).
// https://github.com/anjdreas/UnitsNet
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Linq;
using JetBrains.Annotations;
using UnitsNet.Units;

#if WINDOWS_UWP
using Culture = System.String;
#else
using Culture = System.IFormatProvider;
#endif

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <summary>
    ///     Mostly used for thermal expansion coefficient.
    /// </summary>
    // ReSharper disable once PartialTypeWithSinglePart
#if WINDOWS_UWP
    public sealed partial class PerTemperature
#else
    public partial struct PerTemperature : IComparable, IComparable<PerTemperature>
#endif
    {
        /// <summary>
        ///     Base unit of PerTemperature.
        /// </summary>
        private readonly double _perKelvins;

#if WINDOWS_UWP
        public PerTemperature() : this(0)
        {
        }
#endif

        public PerTemperature(double perkelvins)
        {
            _perKelvins = Convert.ToDouble(perkelvins);
        }

        // Method overloads and with same number of parameters not supported in Universal Windows Platform (WinRT Components).
#if WINDOWS_UWP
        private
#else
        public
#endif
        PerTemperature(long perkelvins)
        {
            _perKelvins = Convert.ToDouble(perkelvins);
        }

        // Method overloads and with same number of parameters not supported in Universal Windows Platform (WinRT Components).
        // Decimal type not supported in Universal Windows Platform (WinRT Components).
#if WINDOWS_UWP
        private
#else
        public
#endif
        PerTemperature(decimal perkelvins)
        {
            _perKelvins = Convert.ToDouble(perkelvins);
        }

        #region Properties

        public static PerTemperatureUnit BaseUnit
        {
            get { return PerTemperatureUnit.PerKelvin; }
        }

        /// <summary>
        ///     Get PerTemperature in PerDegreesCelsius.
        /// </summary>
        public double PerDegreesCelsius
        {
            get { return 1/(1/_perKelvins - 273.15); }
        }

        /// <summary>
        ///     Get PerTemperature in PerDegreesDelisle.
        /// </summary>
        public double PerDegreesDelisle
        {
            get { return 1/((1/_perKelvins - 373.15)*-3/2); }
        }

        /// <summary>
        ///     Get PerTemperature in PerDegreesFahrenheit.
        /// </summary>
        public double PerDegreesFahrenheit
        {
            get { return 1/((1/_perKelvins - 459.67*5/9)*9/5); }
        }

        /// <summary>
        ///     Get PerTemperature in PerDegreesNewton.
        /// </summary>
        public double PerDegreesNewton
        {
            get { return 1/((1/_perKelvins - 273.15)*33/100); }
        }

        /// <summary>
        ///     Get PerTemperature in PerDegreesRankine.
        /// </summary>
        public double PerDegreesRankine
        {
            get { return 1/(1/_perKelvins*9/5); }
        }

        /// <summary>
        ///     Get PerTemperature in PerDegreesReaumur.
        /// </summary>
        public double PerDegreesReaumur
        {
            get { return 1/((1/_perKelvins - 273.15)*4/5); }
        }

        /// <summary>
        ///     Get PerTemperature in PerDegreesRoemer.
        /// </summary>
        public double PerDegreesRoemer
        {
            get { return 1/((1/_perKelvins - (273.15 - 7.5*40d/21))*21/40); }
        }

        /// <summary>
        ///     Get PerTemperature in PerKelvins.
        /// </summary>
        public double PerKelvins
        {
            get { return _perKelvins; }
        }

        #endregion

        #region Static

        public static PerTemperature Zero
        {
            get { return new PerTemperature(); }
        }

        /// <summary>
        ///     Get PerTemperature from PerDegreesCelsius.
        /// </summary>
        public static PerTemperature FromPerDegreesCelsius(double perdegreescelsius)
        {
            return new PerTemperature(1/(1/perdegreescelsius + 273.15));
        }

        /// <summary>
        ///     Get PerTemperature from PerDegreesDelisle.
        /// </summary>
        public static PerTemperature FromPerDegreesDelisle(double perdegreesdelisle)
        {
            return new PerTemperature(1/(1/perdegreesdelisle*-2/3 + 373.15));
        }

        /// <summary>
        ///     Get PerTemperature from PerDegreesFahrenheit.
        /// </summary>
        public static PerTemperature FromPerDegreesFahrenheit(double perdegreesfahrenheit)
        {
            return new PerTemperature(1/(1/perdegreesfahrenheit*5/9 + 459.67*5/9));
        }

        /// <summary>
        ///     Get PerTemperature from PerDegreesNewton.
        /// </summary>
        public static PerTemperature FromPerDegreesNewton(double perdegreesnewton)
        {
            return new PerTemperature(1/(1/perdegreesnewton*100/33 + 273.15));
        }

        /// <summary>
        ///     Get PerTemperature from PerDegreesRankine.
        /// </summary>
        public static PerTemperature FromPerDegreesRankine(double perdegreesrankine)
        {
            return new PerTemperature(1/(1/perdegreesrankine*5/9));
        }

        /// <summary>
        ///     Get PerTemperature from PerDegreesReaumur.
        /// </summary>
        public static PerTemperature FromPerDegreesReaumur(double perdegreesreaumur)
        {
            return new PerTemperature(1/(1/perdegreesreaumur*5/4 + 273.15));
        }

        /// <summary>
        ///     Get PerTemperature from PerDegreesRoemer.
        /// </summary>
        public static PerTemperature FromPerDegreesRoemer(double perdegreesroemer)
        {
            return new PerTemperature(1/(1/perdegreesroemer*40/21 + 273.15 - 7.5*40d/21));
        }

        /// <summary>
        ///     Get PerTemperature from PerKelvins.
        /// </summary>
        public static PerTemperature FromPerKelvins(double perkelvins)
        {
            return new PerTemperature(perkelvins);
        }

#if !WINDOWS_UWP
        /// <summary>
        ///     Get nullable PerTemperature from nullable PerDegreesCelsius.
        /// </summary>
        public static PerTemperature? FromPerDegreesCelsius(double? perdegreescelsius)
        {
            if (perdegreescelsius.HasValue)
            {
                return FromPerDegreesCelsius(perdegreescelsius.Value);
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        ///     Get nullable PerTemperature from nullable PerDegreesDelisle.
        /// </summary>
        public static PerTemperature? FromPerDegreesDelisle(double? perdegreesdelisle)
        {
            if (perdegreesdelisle.HasValue)
            {
                return FromPerDegreesDelisle(perdegreesdelisle.Value);
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        ///     Get nullable PerTemperature from nullable PerDegreesFahrenheit.
        /// </summary>
        public static PerTemperature? FromPerDegreesFahrenheit(double? perdegreesfahrenheit)
        {
            if (perdegreesfahrenheit.HasValue)
            {
                return FromPerDegreesFahrenheit(perdegreesfahrenheit.Value);
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        ///     Get nullable PerTemperature from nullable PerDegreesNewton.
        /// </summary>
        public static PerTemperature? FromPerDegreesNewton(double? perdegreesnewton)
        {
            if (perdegreesnewton.HasValue)
            {
                return FromPerDegreesNewton(perdegreesnewton.Value);
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        ///     Get nullable PerTemperature from nullable PerDegreesRankine.
        /// </summary>
        public static PerTemperature? FromPerDegreesRankine(double? perdegreesrankine)
        {
            if (perdegreesrankine.HasValue)
            {
                return FromPerDegreesRankine(perdegreesrankine.Value);
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        ///     Get nullable PerTemperature from nullable PerDegreesReaumur.
        /// </summary>
        public static PerTemperature? FromPerDegreesReaumur(double? perdegreesreaumur)
        {
            if (perdegreesreaumur.HasValue)
            {
                return FromPerDegreesReaumur(perdegreesreaumur.Value);
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        ///     Get nullable PerTemperature from nullable PerDegreesRoemer.
        /// </summary>
        public static PerTemperature? FromPerDegreesRoemer(double? perdegreesroemer)
        {
            if (perdegreesroemer.HasValue)
            {
                return FromPerDegreesRoemer(perdegreesroemer.Value);
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        ///     Get nullable PerTemperature from nullable PerKelvins.
        /// </summary>
        public static PerTemperature? FromPerKelvins(double? perkelvins)
        {
            if (perkelvins.HasValue)
            {
                return FromPerKelvins(perkelvins.Value);
            }
            else
            {
                return null;
            }
        }

#endif

        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="PerTemperatureUnit" /> to <see cref="PerTemperature" />.
        /// </summary>
        /// <param name="val">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>PerTemperature unit value.</returns>
        public static PerTemperature From(double val, PerTemperatureUnit fromUnit)
        {
            switch (fromUnit)
            {
                case PerTemperatureUnit.PerDegreeCelsius:
                    return FromPerDegreesCelsius(val);
                case PerTemperatureUnit.PerDegreeDelisle:
                    return FromPerDegreesDelisle(val);
                case PerTemperatureUnit.PerDegreeFahrenheit:
                    return FromPerDegreesFahrenheit(val);
                case PerTemperatureUnit.PerDegreeNewton:
                    return FromPerDegreesNewton(val);
                case PerTemperatureUnit.PerDegreeRankine:
                    return FromPerDegreesRankine(val);
                case PerTemperatureUnit.PerDegreeReaumur:
                    return FromPerDegreesReaumur(val);
                case PerTemperatureUnit.PerDegreeRoemer:
                    return FromPerDegreesRoemer(val);
                case PerTemperatureUnit.PerKelvin:
                    return FromPerKelvins(val);

                default:
                    throw new NotImplementedException("fromUnit: " + fromUnit);
            }
        }

#if !WINDOWS_UWP
        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="PerTemperatureUnit" /> to <see cref="PerTemperature" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>PerTemperature unit value.</returns>
        public static PerTemperature? From(double? value, PerTemperatureUnit fromUnit)
        {
            if (!value.HasValue)
            {
                return null;
            }
            switch (fromUnit)
            {
                case PerTemperatureUnit.PerDegreeCelsius:
                    return FromPerDegreesCelsius(value.Value);
                case PerTemperatureUnit.PerDegreeDelisle:
                    return FromPerDegreesDelisle(value.Value);
                case PerTemperatureUnit.PerDegreeFahrenheit:
                    return FromPerDegreesFahrenheit(value.Value);
                case PerTemperatureUnit.PerDegreeNewton:
                    return FromPerDegreesNewton(value.Value);
                case PerTemperatureUnit.PerDegreeRankine:
                    return FromPerDegreesRankine(value.Value);
                case PerTemperatureUnit.PerDegreeReaumur:
                    return FromPerDegreesReaumur(value.Value);
                case PerTemperatureUnit.PerDegreeRoemer:
                    return FromPerDegreesRoemer(value.Value);
                case PerTemperatureUnit.PerKelvin:
                    return FromPerKelvins(value.Value);

                default:
                    throw new NotImplementedException("fromUnit: " + fromUnit);
            }
        }
#endif

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        [UsedImplicitly]
        public static string GetAbbreviation(PerTemperatureUnit unit)
        {
            return GetAbbreviation(unit, null);
        }

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <param name="culture">Culture to use for localization. Defaults to Thread.CurrentUICulture.</param>
        /// <returns>Unit abbreviation string.</returns>
        [UsedImplicitly]
        public static string GetAbbreviation(PerTemperatureUnit unit, [CanBeNull] Culture culture)
        {
            return UnitSystem.GetCached(culture).GetDefaultAbbreviation(unit);
        }

        #endregion

        #region Arithmetic Operators

#if !WINDOWS_UWP
        public static PerTemperature operator -(PerTemperature right)
        {
            return new PerTemperature(-right._perKelvins);
        }

        public static PerTemperature operator +(PerTemperature left, PerTemperature right)
        {
            return new PerTemperature(left._perKelvins + right._perKelvins);
        }

        public static PerTemperature operator -(PerTemperature left, PerTemperature right)
        {
            return new PerTemperature(left._perKelvins - right._perKelvins);
        }

        public static PerTemperature operator *(double left, PerTemperature right)
        {
            return new PerTemperature(left*right._perKelvins);
        }

        public static PerTemperature operator *(PerTemperature left, double right)
        {
            return new PerTemperature(left._perKelvins*(double)right);
        }

        public static PerTemperature operator /(PerTemperature left, double right)
        {
            return new PerTemperature(left._perKelvins/(double)right);
        }

        public static double operator /(PerTemperature left, PerTemperature right)
        {
            return Convert.ToDouble(left._perKelvins/right._perKelvins);
        }
#endif

        #endregion

        #region Equality / IComparable

        public int CompareTo(object obj)
        {
            if (obj == null) throw new ArgumentNullException("obj");
            if (!(obj is PerTemperature)) throw new ArgumentException("Expected type PerTemperature.", "obj");
            return CompareTo((PerTemperature) obj);
        }

#if WINDOWS_UWP
        internal
#else
        public
#endif
        int CompareTo(PerTemperature other)
        {
            return _perKelvins.CompareTo(other._perKelvins);
        }

#if !WINDOWS_UWP
        public static bool operator <=(PerTemperature left, PerTemperature right)
        {
            return left._perKelvins <= right._perKelvins;
        }

        public static bool operator >=(PerTemperature left, PerTemperature right)
        {
            return left._perKelvins >= right._perKelvins;
        }

        public static bool operator <(PerTemperature left, PerTemperature right)
        {
            return left._perKelvins < right._perKelvins;
        }

        public static bool operator >(PerTemperature left, PerTemperature right)
        {
            return left._perKelvins > right._perKelvins;
        }

        public static bool operator ==(PerTemperature left, PerTemperature right)
        {
            // ReSharper disable once CompareOfFloatsByEqualityOperator
            return left._perKelvins == right._perKelvins;
        }

        public static bool operator !=(PerTemperature left, PerTemperature right)
        {
            // ReSharper disable once CompareOfFloatsByEqualityOperator
            return left._perKelvins != right._perKelvins;
        }
#endif

        public override bool Equals(object obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }

            return _perKelvins.Equals(((PerTemperature) obj)._perKelvins);
        }

        public override int GetHashCode()
        {
            return _perKelvins.GetHashCode();
        }

        #endregion

        #region Conversion

        /// <summary>
        ///     Convert to the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>Value in new unit if successful, exception otherwise.</returns>
        /// <exception cref="NotImplementedException">If conversion was not successful.</exception>
        public double As(PerTemperatureUnit unit)
        {
            switch (unit)
            {
                case PerTemperatureUnit.PerDegreeCelsius:
                    return PerDegreesCelsius;
                case PerTemperatureUnit.PerDegreeDelisle:
                    return PerDegreesDelisle;
                case PerTemperatureUnit.PerDegreeFahrenheit:
                    return PerDegreesFahrenheit;
                case PerTemperatureUnit.PerDegreeNewton:
                    return PerDegreesNewton;
                case PerTemperatureUnit.PerDegreeRankine:
                    return PerDegreesRankine;
                case PerTemperatureUnit.PerDegreeReaumur:
                    return PerDegreesReaumur;
                case PerTemperatureUnit.PerDegreeRoemer:
                    return PerDegreesRoemer;
                case PerTemperatureUnit.PerKelvin:
                    return PerKelvins;

                default:
                    throw new NotImplementedException("unit: " + unit);
            }
        }

        #endregion

        #region Parsing

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        public static PerTemperature Parse(string str)
        {
            return Parse(str, null);
        }

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="culture">Format to use when parsing number and unit. If it is null, it defaults to <see cref="NumberFormatInfo.CurrentInfo"/> for parsing the number and <see cref="CultureInfo.CurrentUICulture"/> for parsing the unit abbreviation by culture/language.</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        public static PerTemperature Parse(string str, [CanBeNull] Culture culture)
        {
            if (str == null) throw new ArgumentNullException("str");

#if WINDOWS_UWP
            IFormatProvider formatProvider = culture == null ? null : new CultureInfo(culture);
#else
            IFormatProvider formatProvider = culture;
#endif
            return UnitParser.ParseUnit<PerTemperature>(str, formatProvider,
                delegate(string value, string unit, IFormatProvider formatProvider2)
                {
                    double parsedValue = double.Parse(value, formatProvider2);
                    PerTemperatureUnit parsedUnit = ParseUnit(unit, formatProvider2);
                    return From(parsedValue, parsedUnit);
                }, (x, y) => FromPerKelvins(x.PerKelvins + y.PerKelvins));
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        public static bool TryParse([CanBeNull] string str, out PerTemperature result)
        {
            return TryParse(str, null, out result);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="culture">Format to use when parsing number and unit. If it is null, it defaults to <see cref="NumberFormatInfo.CurrentInfo"/> for parsing the number and <see cref="CultureInfo.CurrentUICulture"/> for parsing the unit abbreviation by culture/language.</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        public static bool TryParse([CanBeNull] string str, [CanBeNull] Culture culture, out PerTemperature result)
        {
            try
            {
                result = Parse(str, culture);
                return true;
            }
            catch
            {
                result = default(PerTemperature);
                return false;
            }
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static PerTemperatureUnit ParseUnit(string str)
        {
            return ParseUnit(str, (IFormatProvider)null);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static PerTemperatureUnit ParseUnit(string str, [CanBeNull] string cultureName)
        {
            return ParseUnit(str, cultureName == null ? null : new CultureInfo(cultureName));
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
#if WINDOWS_UWP
        internal
#else
        public
#endif
        static PerTemperatureUnit ParseUnit(string str, IFormatProvider formatProvider = null)
        {
            if (str == null) throw new ArgumentNullException("str");

            var unitSystem = UnitSystem.GetCached(formatProvider);
            var unit = unitSystem.Parse<PerTemperatureUnit>(str.Trim());

            if (unit == PerTemperatureUnit.Undefined)
            {
                var newEx = new UnitsNetException("Error parsing string. The unit is not a recognized PerTemperatureUnit.");
                newEx.Data["input"] = str;
                newEx.Data["formatprovider"] = formatProvider?.ToString() ?? "(null)";
                throw newEx;
            }

            return unit;
        }

        #endregion

        /// <summary>
        ///     Set the default unit used by ToString(). Default is PerKelvin
        /// </summary>
        public static PerTemperatureUnit ToStringDefaultUnit { get; set; } = PerTemperatureUnit.PerKelvin;

        /// <summary>
        ///     Get default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
        {
            return ToString(ToStringDefaultUnit);
        }

        /// <summary>
        ///     Get string representation of value and unit. Using current UI culture and two significant digits after radix.
        /// </summary>
        /// <param name="unit">Unit representation to use.</param>
        /// <returns>String representation.</returns>
        public string ToString(PerTemperatureUnit unit)
        {
            return ToString(unit, null, 2);
        }

        /// <summary>
        ///     Get string representation of value and unit. Using two significant digits after radix.
        /// </summary>
        /// <param name="unit">Unit representation to use.</param>
        /// <param name="culture">Culture to use for localization and number formatting.</param>
        /// <returns>String representation.</returns>
        public string ToString(PerTemperatureUnit unit, [CanBeNull] Culture culture)
        {
            return ToString(unit, culture, 2);
        }

        /// <summary>
        ///     Get string representation of value and unit.
        /// </summary>
        /// <param name="unit">Unit representation to use.</param>
        /// <param name="culture">Culture to use for localization and number formatting.</param>
        /// <param name="significantDigitsAfterRadix">The number of significant digits after the radix point.</param>
        /// <returns>String representation.</returns>
        [UsedImplicitly]
        public string ToString(PerTemperatureUnit unit, [CanBeNull] Culture culture, int significantDigitsAfterRadix)
        {
            double value = As(unit);
            string format = UnitFormatter.GetFormat(value, significantDigitsAfterRadix);
            return ToString(unit, culture, format);
        }

        /// <summary>
        ///     Get string representation of value and unit.
        /// </summary>
        /// <param name="culture">Culture to use for localization and number formatting.</param>
        /// <param name="unit">Unit representation to use.</param>
        /// <param name="format">String format to use. Default:  "{0:0.##} {1} for value and unit abbreviation respectively."</param>
        /// <param name="args">Arguments for string format. Value and unit are implictly included as arguments 0 and 1.</param>
        /// <returns>String representation.</returns>
        [UsedImplicitly]
        public string ToString(PerTemperatureUnit unit, [CanBeNull] Culture culture, [NotNull] string format,
            [NotNull] params object[] args)
        {
            if (format == null) throw new ArgumentNullException(nameof(format));
            if (args == null) throw new ArgumentNullException(nameof(args));

#if WINDOWS_UWP
            IFormatProvider formatProvider = culture == null ? null : new CultureInfo(culture);
#else
            IFormatProvider formatProvider = culture;
#endif
            double value = As(unit);
            object[] formatArgs = UnitFormatter.GetFormatArgs(unit, value, formatProvider, args);
            return string.Format(formatProvider, format, formatArgs);
        }

        /// <summary>
        /// Represents the largest possible value of PerTemperature
        /// </summary>
        public static PerTemperature MaxValue
        {
            get
            {
                return new PerTemperature(double.MaxValue);
            }
        }

        /// <summary>
        /// Represents the smallest possible value of PerTemperature
        /// </summary>
        public static PerTemperature MinValue
        {
            get
            {
                return new PerTemperature(double.MinValue);
            }
        }
    }
}
